[package]
name = "craby_calculator_ios"
version.workspace = true
edition.workspace = true

[dependencies]
objc = { workspace = true }
craby_calculator = { path = "../lib" }

[lib]
name = "crabycalculator"
crate-type = ["staticlib"]
