// Auto generated by Craby. DO NOT EDIT.
#import "{{ cxx_name }}.hpp"

#import <ReactCommon/CxxTurboModuleUtils.h>

@interface {{ mm_name }} : NSObject
@end

@implementation {{ mm_name }}
+ (void)load {
}
@end
