// Auto generated by Craby. DO NOT EDIT.
#import "{{ cxx_name }}.hpp"

#import <ReactCommon/CxxTurboModuleUtils.h>

@interface {{ objc_provider }} : NSObject
@end

@implementation {{ objc_provider }}
+ (void)load {
}
@end
