// Auto generated by Craby. DO NOT EDIT.
use jni::sys::*;

#[no_mangle]
pub extern "C" fn Java_com_calculator_CalculatorModule_nativeAdd(_env: JNIEnv, _class: jobject, a: f64, b: f64) -> f64 {
    craby_calculator::calculator::add(a, b)
}

#[no_mangle]
pub extern "C" fn Java_com_calculator_CalculatorModule_nativeSubtract(_env: JNIEnv, _class: jobject, a: f64, b: f64) -> f64 {
    craby_calculator::calculator::subtract(a, b)
}

#[no_mangle]
pub extern "C" fn Java_com_calculator_CalculatorModule_nativeMultiply(_env: JNIEnv, _class: jobject, a: f64, b: f64) -> f64 {
    craby_calculator::calculator::multiply(a, b)
}

#[no_mangle]
pub extern "C" fn Java_com_calculator_CalculatorModule_nativeDivide(_env: JNIEnv, _class: jobject, a: f64, b: f64) -> f64 {
    craby_calculator::calculator::divide(a, b)
}
