// Auto generated by Craby. DO NOT EDIT.
use jni::sys::*;

#[no_mangle]
pub extern "C" fn Java_com_calculator_CalculatorModule_nativeMultiply(_env: JNIEnv, _class: jobject, a: f64, b: f64) -> f64 {
    craby_calculator::calculator::multiply(a, b)
}
