// Auto generated by Craby. DO NOT EDIT.
pub mod calculator {
    use crate::impls;

    pub fn add(a: f64, b: f64) -> f64 {
        impls::add(a, b)
    }

    pub fn subtract(a: f64, b: f64) -> f64 {
        impls::subtract(a, b)
    }

    pub fn multiply(a: f64, b: f64) -> f64 {
        impls::multiply(a, b)
    }

    pub fn divide(a: f64, b: f64) -> f64 {
        impls::divide(a, b)
    }
}

mod impls;
