use std::path::PathBuf;

use craby_codegen::{
    generator::CodeGenerator,
    platform::rust::{ffi_rs, generated_rs, lib_rs},
    types::schema::Schema,
};
use craby_common::{
    config::load_config,
    constants::{crate_dir, impl_mod_name},
    env::is_initialized,
};
use log::info;

use crate::utils::{file::write_file, schema::print_schema};

pub struct CodegenOptions {
    pub project_root: PathBuf,
    pub schemas: Vec<String>,
}

pub fn perform(opts: CodegenOptions) -> anyhow::Result<()> {
    if !is_initialized(&opts.project_root) {
        anyhow::bail!("Craby project is not initialized. Please run `craby init` first.");
    }

    let crate_path = crate_dir(&opts.project_root);
    let crate_src_path = crate_path.join("src");
    let config = load_config(&opts.project_root)?;

    info!("{} module schema(s) found", opts.schemas.len());

    let generator = CodeGenerator::new();
    let total_mods = opts.schemas.len();
    let mut codegen_res = vec![];

    opts.schemas
        .iter()
        .enumerate()
        .try_for_each(|(i, schema)| -> Result<(), anyhow::Error> {
            let schema = serde_json::from_str::<Schema>(&schema)?;
            println!(
                "Generating for {} module... ({}/{})",
                schema.module_name,
                i + 1,
                total_mods
            );

            if schema.r#type == "Component" {
                return Err(anyhow::anyhow!("Component type is not supported"));
            }

            let res = generator.generate(&schema)?;

            print_schema(&schema, &config)?;
            write_file(
                crate_src_path.join(format!("{}.rs", impl_mod_name(&schema.module_name))),
                format!("{}\n", res.impl_code),
                false,
            )?;

            codegen_res.push(res);

            Ok(())
        })?;

    write_file(
        crate_src_path.join("lib.rs"),
        with_generated_comment(lib_rs(&codegen_res)),
        true,
    )?;
    write_file(
        crate_src_path.join("ffi.rs"),
        with_generated_comment(ffi_rs(&codegen_res)),
        true,
    )?;
    write_file(
        crate_src_path.join("generated.rs"),
        with_generated_comment(generated_rs(&codegen_res)),
        true,
    )?;

    info!("Codegen completed successfully 🎉");

    Ok(())
}

fn with_generated_comment(code: String) -> String {
    ["// Auto generated by Craby. DO NOT EDIT.", &code].join("\n") + "\n"
}
