use std::path::PathBuf;

use craby_codegen::{generator::CodeGenerator, types::schema::Schema};
use craby_common::{
    config::load_config,
    constants::{crate_dir, impl_mod_name, GENERATED_MOD},
    env::is_initialized,
    utils::string::sanitize,
};
use log::info;

use crate::utils::{file::write_file, schema::print_schema};

pub struct CodegenOptions {
    pub project_root: PathBuf,
    pub schemas: Vec<String>,
}

pub fn perform(opts: CodegenOptions) -> anyhow::Result<()> {
    if !is_initialized(&opts.project_root) {
        anyhow::bail!("Craby project is not initialized. Please run `craby init` first.");
    }

    let crate_path = crate_dir(&opts.project_root);
    let crate_src_path = crate_path.join("src");
    let config = load_config(&opts.project_root)?.into_complete();

    info!("{} module schema(s) found", opts.schemas.len());

    let total_mods = opts.schemas.len();
    let mut spec_codes = vec![];
    let mut ffi_codes = vec![];
    let mut mod_imports = vec![format!("pub(crate) mod {};", GENERATED_MOD)];
    let generator = CodeGenerator::new();

    opts.schemas
        .into_iter()
        .enumerate()
        .try_for_each(|(i, schema)| {
            let schema = serde_json::from_str::<Schema>(&schema)?;
            println!(
                "Generating for {} module... ({}/{})",
                schema.module_name,
                i + 1,
                total_mods
            );

            if schema.r#type == "Component" {
                return Err(anyhow::anyhow!("Component type is not supported"));
            }

            print_schema(&schema, &config);

            let sanitized_mod_name = sanitize(&schema.module_name);
            let impl_mod_name = impl_mod_name(&sanitized_mod_name);

            let spec_code = generator.generate_spec(&schema);
            let ffi_code = generator.generate_ffi(&schema);
            let impl_code = generator.generate_impl(&schema);

            spec_codes.push(spec_code);
            ffi_codes.push(ffi_code);
            mod_imports.push(format!("pub(crate) mod {};", impl_mod_name));

            write_file(
                crate_src_path.join(format!("{}.rs", impl_mod_name)),
                impl_code + "\n",
                false,
            )?;

            Ok::<(), anyhow::Error>(())
        })?;

    ffi_codes.push(mod_imports.join("\n"));

    let spec_code = spec_codes.join("\n\n");
    let ffi_code = ffi_codes.join("\n\n");

    write_file(
        crate_src_path.join("lib.rs"),
        with_generated_comment(ffi_code),
        true,
    )?;
    write_file(
        crate_src_path.join(format!("{}.rs", GENERATED_MOD)),
        with_generated_comment(spec_code),
        true,
    )?;

    info!("Codegen completed successfully 🎉");

    Ok(())
}

fn with_generated_comment(code: String) -> String {
    ["// Auto generated by Craby. DO NOT EDIT.", &code].join("\n") + "\n"
}
