use std::path::PathBuf;

use craby_codegen::{
    generator::CodeGenerator,
    platform::rust::{ffi_rs, lib_rs},
    types::schema::Schema,
};
use craby_common::{
    config::load_config,
    constants::{crate_dir, impl_mod_name, FFI_MOD, GENERATED_MOD},
    env::is_initialized,
};
use log::info;

use crate::utils::{file::write_file, schema::print_schema};

pub struct CodegenOptions {
    pub project_root: PathBuf,
    pub schemas: Vec<String>,
}

pub fn perform(opts: CodegenOptions) -> anyhow::Result<()> {
    if !is_initialized(&opts.project_root) {
        anyhow::bail!("Craby project is not initialized. Please run `craby init` first.");
    }

    let crate_path = crate_dir(&opts.project_root);
    let crate_src_path = crate_path.join("src");
    let config = load_config(&opts.project_root)?;

    info!("{} module schema(s) found", opts.schemas.len());

    let total_mods = opts.schemas.len();
    let mut mod_names = vec![];
    let mut spec_codes = vec!["use crate::ffi::ffi::*;".to_string()];
    let mut cxx_bridges = vec![];
    let mut impl_mods = vec![];
    let generator = CodeGenerator::new();

    opts.schemas
        .into_iter()
        .enumerate()
        .try_for_each(|(i, schema)| {
            let schema = serde_json::from_str::<Schema>(&schema)?;
            println!(
                "Generating for {} module... ({}/{})",
                schema.module_name,
                i + 1,
                total_mods
            );

            if schema.r#type == "Component" {
                return Err(anyhow::anyhow!("Component type is not supported"));
            }

            print_schema(&schema, &config)?;

            let impl_mod_name = impl_mod_name(&schema.module_name);
            let spec_code = generator.generate_spec(&schema)?;
            let impl_code = generator.generate_impl(&schema)?;
            cxx_bridges.extend(generator.get_cxx_bridge_funcs(&schema)?);

            spec_codes.push(spec_code);
            impl_mods.push(format!("pub(crate) mod {};", impl_mod_name));
            mod_names.push(schema.module_name.clone());

            write_file(
                crate_src_path.join(format!("{}.rs", impl_mod_name)),
                impl_code + "\n",
                false,
            )?;

            Ok::<(), anyhow::Error>(())
        })?;

    let spec_code = spec_codes.join("\n\n");

    write_file(
        crate_src_path.join("lib.rs"),
        with_generated_comment(lib_rs(&mod_names)),
        true,
    )?;
    write_file(
        crate_src_path.join(format!("{}.rs", FFI_MOD)),
        with_generated_comment(ffi_rs(&mod_names, &cxx_bridges)),
        true,
    )?;
    write_file(
        crate_src_path.join(format!("{}.rs", GENERATED_MOD)),
        with_generated_comment(spec_code),
        true,
    )?;

    info!("Codegen completed successfully 🎉");

    Ok(())
}

fn with_generated_comment(code: String) -> String {
    ["// Auto generated by Craby. DO NOT EDIT.", &code].join("\n") + "\n"
}
