use std::{fs, path::PathBuf};

use craby_codegen::{generator::CodeGenerator, types::schema::Schema};
use craby_common::{
    config::load_config,
    constants::GENERATED_MOD,
    env::is_initialized,
    utils::{sanitize_str, to_impl_mod_name},
};
use log::{debug, info, warn};

use crate::utils::schema::print_schema;

pub struct CodegenOptions {
    pub project_root: PathBuf,
    pub lib_name: String,
    pub java_package_name: String,
    pub schemas: Vec<String>,
}

pub fn r#impl(opts: CodegenOptions) -> anyhow::Result<()> {
    if !is_initialized(&opts.project_root) {
        anyhow::bail!("Craby project is not initialized. Please run `craby init` first.");
    }

    let config = load_config(&opts.project_root)?;
    let config = config.into_complete();

    info!("{} module schema(s) found", opts.schemas.len());

    let total_mods = opts.schemas.len();
    let mut lib_codes = vec![];
    let mut ffi_codes = vec![];
    let mut mod_imports = vec![format!("pub(crate) mod {};", GENERATED_MOD)];
    let generator = CodeGenerator::new();

    opts.schemas
        .into_iter()
        .enumerate()
        .try_for_each(|(i, schema)| {
            let schema = serde_json::from_str::<Schema>(&schema)?;
            println!(
                "Generating {} module... ({}/{})",
                schema.module_name,
                i + 1,
                total_mods
            );

            if schema.r#type == "Component" {
                warn!("Component is not supported yet. Skipping...");
                return Ok(());
            }

            print_schema(&schema, &config);

            let sanitized_mod_name = sanitize_str(&schema.module_name);
            let impl_mod_name = to_impl_mod_name(&sanitized_mod_name);

            let lib_code = generator.generate_module(&schema);
            let ffi_code = generator.generate_ffi_module(&schema);
            let empty_code = generator.generate_empty_module(&schema);

            lib_codes.push(lib_code);
            ffi_codes.push(ffi_code);
            mod_imports.push(format!("pub(crate) mod {};", impl_mod_name));

            write_impl_rs(
                &opts.project_root,
                &schema.module_name,
                &format!("{}.rs", impl_mod_name),
                empty_code + "\n",
            )?;

            Ok::<(), anyhow::Error>(())
        })?;

    ffi_codes.push(mod_imports.join("\n"));

    let lib_code = lib_codes.join("\n\n");
    let ffi_code = ffi_codes.join("\n\n");

    write_rs(&opts.project_root, "lib.rs", ffi_code + "\n")?;
    write_rs(
        &opts.project_root,
        format!("{}.rs", GENERATED_MOD).as_str(),
        lib_code + "\n",
    )?;

    info!("Codegen completed successfully 🎉");

    Ok(())
}

fn write_rs(project_root: &PathBuf, file_name: &str, code: String) -> Result<(), anyhow::Error> {
    let rs_file = project_root
        .join("crates")
        .join("lib")
        .join("src")
        .join(file_name);

    fs::write(
        &rs_file,
        ["// Auto generated by Craby. DO NOT EDIT.", &code].join("\n"),
    )?;
    debug!("Code written to: {}", rs_file.display());

    Ok(())
}

fn write_impl_rs(
    project_root: &PathBuf,
    module_name: &String,
    file_name: &str,
    code: String,
) -> Result<(), anyhow::Error> {
    let rs_file = project_root
        .join("crates")
        .join("lib")
        .join("src")
        .join(file_name);

    if fs::exists(&rs_file)? {
        debug!("{} already exists. Skipping...", rs_file.display());
        return Ok(());
    }

    fs::write(
        &rs_file,
        [
            format!("// Implement module for '{}' here", module_name),
            code,
        ]
        .join("\n"),
    )?;
    debug!("Code written to: {}", rs_file.display());

    Ok(())
}
