nmHoistingLimits: workspaces

nodeLinker: node-modules

compressionLevel: mixed

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
