compressionLevel: mixed

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
