compressionLevel: mixed

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  '@react-native/codegen@*':
    dependencies:
      # For PnP environment
      # - `@babel/parser` is required by `@react-native/codegen`
      '@babel/parser': '^7'

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
    - arm
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
