owners = ["Geunhyeok LEE"]
push = false
publish = true
allow-branch = [
    "release/*",
    "main",
]
shared-version = true
consolidate-commits = true
dependent-version = "fix"

[[pre-release-replacements]]
file = "Cargo.toml"
search = '^(craby_[a-zA-Z0-9_]+)\s*=\s*\{([^}]*)path\s*=\s*"[^"]+"(,?[^}]*)?\}'
replace = '${1} = { version = "{{version}}"${3}}'
min = 0
