// Auto generated by Craby. DO NOT EDIT.
#[no_mangle]
pub extern "C" fn numericMethod(arg: f64) -> f64 {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}
