// Auto generated by Craby. DO NOT EDIT.
use std::os::raw::*;

#[no_mangle]
pub extern "C" fn numericMethod(arg: c_double) -> c_double {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}
