// Auto generated by Craby. DO NOT EDIT.
pub mod basic {
    use crate::basic_impl;

    pub fn numeric_method(arg: f64) -> f64 {
        basic_impl::numeric_method(arg)
    }

    pub fn boolean_method(arg: bool) -> bool {
        basic_impl::boolean_method(arg)
    }
}
