// Auto generated by Craby. DO NOT EDIT.
use std::os::raw::*;

#[no_mangle]
pub extern "C" fn numericMethod(arg: f64) -> f64 {
    generated::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    generated::basic::boolean_method(arg)
}

pub(crate) mod generated;
pub(crate) mod basic_impl;
