// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::{{ snake_name }}_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::bridging")]
pub mod bridging {
    extern "Rust" {
    }
}
