// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::ffi::bridging::*;
use crate::types::*;

pub trait {{ module_name }}Spec {
    fn new(id: usize) -> Self;
    fn id(&self) -> usize;
}
