/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function build(opts: CommonOptions): void

export declare function clean(opts: CommonOptions): void

export declare function codegen(opts: CommonOptions): void

export interface CommonOptions {
  projectRoot: string
  templateBasePath: string
  packageName: string
}

export declare function debug(message: string): void

export declare function doctor(opts: CommonOptions): void

export declare function error(message: string): void

export declare function info(message: string): void

export declare function init(opts: CommonOptions): void

export declare function setup(levelFilter?: string | undefined | null): void

export declare function show(opts: CommonOptions): void

export declare function trace(message: string): void

export declare function warn(message: string): void
