[package]
name = "basic_module_android"
version.workspace = true
edition.workspace = true

[dependencies]
craby_core = { workspace = true, features = ["android"] }
basic_module = { path = "../lib" }

[lib]
name = "basicmodule"
crate-type = ["cdylib"]
