// Auto generated by Craby. DO NOT EDIT.
#[no_mangle]
pub extern "C" fn add(a: f64, b: f64) -> f64 {
    craby_calculator::calculator::add(a, b)
}

#[no_mangle]
pub extern "C" fn subtract(a: f64, b: f64) -> f64 {
    craby_calculator::calculator::subtract(a, b)
}

#[no_mangle]
pub extern "C" fn multiply(a: f64, b: f64) -> f64 {
    craby_calculator::calculator::multiply(a, b)
}

#[no_mangle]
pub extern "C" fn divide(a: f64, b: f64) -> f64 {
    craby_calculator::calculator::divide(a, b)
}
