[package]
name = "basic_module_ios"
version.workspace = true
edition.workspace = true

[dependencies]
objc = { workspace = true }
basic_module = { path = "../lib" }

[lib]
name = "basicmodule"
crate-type = ["staticlib"]
