[package]
name = "basic_module_ios"
version.workspace = true
edition.workspace = true

[dependencies]
craby_core = { workspace = true, features = ["ios"] }
basic_module = { path = "../lib" }

[lib]
name = "basicmodule"
crate-type = ["staticlib"]
