// Auto generated by Craby. DO NOT EDIT.
use crate::craby_test_impl::*;
use crate::generated::*;

#[cxx::bridge(namespace = "craby::codegen::crabytest")]
pub mod ffi {
    extern "Rust" {
        #[cxx_name = "numericMethod"]
        fn numeric_method(arg: f64) -> f64;

        #[cxx_name = "booleanMethod"]
        fn boolean_method(arg: bool) -> bool;

        #[cxx_name = "stringMethod"]
        fn string_method(arg: String) -> String;
    }
}

fn numeric_method(arg: f64) -> f64 {
    CrabyTest::numeric_method(arg)
}

fn boolean_method(arg: bool) -> bool {
    CrabyTest::boolean_method(arg)
}

fn string_method(arg: String) -> String {
    CrabyTest::string_method(arg)
}
