// Auto generated by Craby. DO NOT EDIT.
use ffi::*;

use crate::craby_test_impl::*;
use crate::generated::*;

#[cxx::bridge(namespace = "craby::codegen::crabytest")]
pub mod ffi {
    struct TestObject {
        foo: String,
        bar: f64,
        baz: bool,
    }

    extern "Rust" {
        #[cxx_name = "numericMethod"]
        fn numeric_method(arg: f64) -> f64;

        #[cxx_name = "booleanMethod"]
        fn boolean_method(arg: bool) -> bool;

        #[cxx_name = "stringMethod"]
        fn string_method(arg: String) -> String;

        #[cxx_name = "objectMethod"]
        fn object_method(arg: TestObject) -> TestObject;
    }
}

fn numeric_method(arg: f64) -> f64 {
    CrabyTest::numeric_method(arg)
}

fn boolean_method(arg: bool) -> bool {
    CrabyTest::boolean_method(arg)
}

fn string_method(arg: String) -> String {
    CrabyTest::string_method(arg)
}

fn object_method(arg: TestObject) -> TestObject {
    CrabyTest::object_method(arg)
}
