// Auto generated by Craby. DO NOT EDIT.
use ffi::*;
use crate::generated::*;
use crate::craby_test_impl::*;

#[cxx::bridge(namespace = "craby::crabytest")]
pub mod craby_test {
    // Type definitions
    // N/A

    extern "Rust" {
        #[cxx_name = "numericMethod"]
        fn craby_test_numeric_method(arg: f64) -> f64;

        #[cxx_name = "booleanMethod"]
        fn craby_test_boolean_method(arg: bool) -> bool;

        #[cxx_name = "stringMethod"]
        fn craby_test_string_method(arg: String) -> String;

        #[cxx_name = "objectMethod"]
        fn craby_test_object_method(arg: ());

        #[cxx_name = "arrayMethod"]
        fn craby_test_array_method(arg: Vec<f64>) -> Vec<f64>;

        #[cxx_name = "enumMethod"]
        fn craby_test_enum_method(arg: MyEnum) -> String;

        #[cxx_name = "promiseMethod"]
        fn craby_test_promise_method(arg: f64) -> Result<f64>;
    }
}

fn craby_test_numeric_method(arg: f64) -> f64 {
    CrabyTest::numeric_method(arg)
}

fn craby_test_boolean_method(arg: bool) -> bool {
    CrabyTest::boolean_method(arg)
}

fn craby_test_string_method(arg: String) -> String {
    CrabyTest::string_method(arg)
}

fn craby_test_object_method(arg: ()) {
    CrabyTest::object_method(arg)
}

fn craby_test_array_method(arg: Vec<f64>) -> Vec<f64> {
    CrabyTest::array_method(arg)
}

fn craby_test_enum_method(arg: MyEnum) -> String {
    CrabyTest::enum_method(arg)
}

fn craby_test_promise_method(arg: f64) -> Result<f64, anyhow::Error> {
    CrabyTest::promise_method(arg)
}
