// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use crate::ffi::bridging::*;
use crate::types::*;

pub trait CrabyTestSpec {
    fn numeric_method(arg: Number) -> Number;
    fn boolean_method(arg: Boolean) -> Boolean;
    fn string_method(arg: String) -> String;
    fn object_method(arg: TestObject) -> TestObject;
    fn array_method(arg: Array<Number>) -> Array<Number>;
    fn enum_method(arg: MyEnum) -> String;
    fn nullable_method(arg: Nullable<Number>) -> Nullable<Number>;
    fn promise_method(arg: Number) -> Promise<Number>;
}

impl Default for MyEnum {
    fn default() -> Self {
        MyEnum::FOO
    }
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default()
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or(String::default()),
            null,
        }
    }
}

impl Default for SubObject {
    fn default() -> Self {
        SubObject {
            a: NullableString::default(),
            b: 0.0,
            c: false
        }
    }
}

impl Default for NullableSubObject {
    fn default() -> Self {
        NullableSubObject {
            null: true,
            val: SubObject::default()
        }
    }
}

impl From<NullableSubObject> for Nullable<SubObject> {
    fn from(val: NullableSubObject) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<SubObject>> for NullableSubObject {
    fn from(val: Nullable<SubObject>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableSubObject {
            val: val.unwrap_or(SubObject::default()),
            null,
        }
    }
}

impl Default for TestObject {
    fn default() -> Self {
        TestObject {
            foo: String::default(),
            bar: 0.0,
            baz: false,
            sub: NullableSubObject::default()
        }
    }
}

impl Default for NullableNumber {
    fn default() -> Self {
        NullableNumber {
            null: true,
            val: 0.0
        }
    }
}

impl From<NullableNumber> for Nullable<Number> {
    fn from(val: NullableNumber) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<Number>> for NullableNumber {
    fn from(val: Nullable<Number>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableNumber {
            val: val.unwrap_or(0.0),
            null,
        }
    }
}
