// Auto generated by Craby. DO NOT EDIT.
use generated::*;
use std::os::raw::*;
use std::ffi::{CStr, CString};

#[no_mangle]
pub extern "C" fn numericMethod(arg: f64) -> f64 {
    craby_test_impl::CrabyTest::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    craby_test_impl::CrabyTest::boolean_method(arg)
}

#[no_mangle]
pub extern "C" fn stringMethod(arg: *const c_char) -> *const c_char {
    let arg = unsafe { CStr::from_ptr(arg) }.to_string_lossy().into_owned();
    let ret = craby_test_impl::CrabyTest::string_method(arg);
    CString::new(ret.as_str()).unwrap().into_raw()
}

pub(crate) mod generated;
pub(crate) mod craby_test_impl;
