// Auto generated by Craby. DO NOT EDIT.
use generated::*;
use std::os::raw::*;

#[no_mangle]
pub extern "C" fn numericMethod(arg: f64) -> f64 {
    craby_test_impl::CrabyTest::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(arg: bool) -> bool {
    craby_test_impl::CrabyTest::boolean_method(arg)
}

pub(crate) mod generated;
pub(crate) mod craby_test_impl;
