// Auto generated by Craby. DO NOT EDIT.
pub type Number = f64;
pub type Boolean = bool;
pub type String = std::string::String;
pub type Array<T> = Vec<T>;
pub type Promise<T> = Result<T, anyhow::Error>;

pub mod promise {
    use super::Promise;

    pub fn resolve<T>(val: T) -> Promise<T> {
        Ok(val)
    }

    pub fn rejected<T>(err: impl AsRef<str>) -> Promise<T> {
        Err(anyhow::anyhow!(err.as_ref().to_string()))
    }
}

pub trait Nullable<T> {
    fn new(val: Option<T>) -> Self;
    fn value(self, val: T) -> Self;
    fn value_of(&self) -> Option<T>;
}
