// Auto generated by Craby. DO NOT EDIT.
use craby_core::jni::sys::*;
use craby_core::jni::{objects::JObject, JNIEnv};

#[no_mangle]
pub extern "C" fn numericMethod(_env: JNIEnv, _class: JObject, arg: jdouble) -> jdouble {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn booleanMethod(_env: JNIEnv, _class: JObject, arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}
