// Auto generated by Craby. DO NOT EDIT.
use jni::sys::*;

#[no_mangle]
pub extern "C" fn Java_com_basic_BasicModule_nativeNumericMethod(_env: JNIEnv, _class: jobject, arg: f64) -> f64 {
    basic_module::basic::numeric_method(arg)
}

#[no_mangle]
pub extern "C" fn Java_com_basic_BasicModule_nativeBooleanMethod(_env: JNIEnv, _class: jobject, arg: bool) -> bool {
    basic_module::basic::boolean_method(arg)
}
