// swift-tools-version: 6.0
// Auto generated by Craby. DO NOT EDIT.
// React Native resolves this package through build/generated/autolinking/libs/CrabyTest.

import PackageDescription

let package = Package(
    name: "CrabyTest",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "CrabyTest", targets: ["CrabyTest"]),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
    ],
    targets: [
        .binaryTarget(
            name: "CrabyTestRust",
            path: "ios/framework/libcrabytest.xcframework"
        ),
        .target(
            name: "CrabyTest",
            dependencies: [
                .target(name: "CrabyTestRust"),
                .product(name: "ReactHeaders", package: "ReactNative"),
                .product(name: "ReactNativeHeaders", package: "ReactNative"),
                .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
            ],
            path: ".",
            exclude: ["node_modules"],
            sources: [
                "ios/CrabyTestModuleProvider.mm",
                "ios/src/ffi.rs.cc",
                "cpp/CxxCalculatorModule.cpp",
                "cpp/CxxCrabyTestModule.cpp"
            ],
            publicHeadersPath: "ios/include",
            cxxSettings: [
                .headerSearchPath("cpp"),
                .headerSearchPath("ios/include"),
                .define("DEBUG", .when(configuration: .debug)),
                .define("NDEBUG", .when(configuration: .release)),
            ],
            linkerSettings: [
                .linkedFramework("UIKit"),
                .linkedFramework("Foundation"),
                .linkedFramework("CoreGraphics"),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
