// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <react/bridging/Bridging.h>
#include "cxx.h"
#include "ffi.rs.h"

using namespace facebook;

namespace facebook {
namespace react {

template <typename T>
struct Bridging<rust::Vec<T>> {
  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> vec;
    vec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto element = arr.getValueAtIndex(rt, i);
      vec.push_back(react::bridging::fromJs<T>(rt, element, callInvoker));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto jsElement = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, jsElement);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::crabytest::TestObject> {
  static craby::crabytest::TestObject fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$foo = obj.getProperty(rt, "foo");
    auto obj$bar = obj.getProperty(rt, "bar");
    auto obj$baz = obj.getProperty(rt, "baz");

    auto _obj$foo = react::bridging::fromJs<std::string>(rt, obj$foo, callInvoker);
    auto _obj$bar = react::bridging::fromJs<double>(rt, obj$bar, callInvoker);
    auto _obj$baz = react::bridging::fromJs<bool>(rt, obj$baz, callInvoker);

    craby::crabytest::TestObject ret = {
      _obj$foo,
      _obj$bar,
      _obj$baz
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::crabytest::TestObject value) {
    jsi::Object obj = jsi::Object(rt);
    auto _obj$foo = react::bridging::toJs(rt, std::string(value.foo));
    auto _obj$bar = react::bridging::toJs(rt, value.bar);
    auto _obj$baz = react::bridging::toJs(rt, value.baz);

    obj.setProperty(rt, "foo", _obj$foo);
    obj.setProperty(rt, "bar", _obj$bar);
    obj.setProperty(rt, "baz", _obj$baz);

    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::crabytest::MyEnum> {
  static craby::crabytest::MyEnum fromJs(jsi::Runtime &rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto raw = value.asString(rt).utf8(rt);
    if (raw == "FOO") {
      return craby::crabytest::MyEnum::FOO;
    } else if (raw == "BAR") {
      return craby::crabytest::MyEnum::BAR;
    } else if (raw == "BAZ") {
      return craby::crabytest::MyEnum::BAZ;
    } else {
      throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::crabytest::MyEnum value) {
    switch (value) {
      case craby::crabytest::MyEnum::FOO:
        return react::bridging::toJs(rt, "FOO");
      case craby::crabytest::MyEnum::BAR:
        return react::bridging::toJs(rt, "BAR");
      case craby::crabytest::MyEnum::BAZ:
        return react::bridging::toJs(rt, "BAZ");
      default:
        throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }
};

} // namespace react
} // namespace facebook
