// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <react/bridging/Bridging.h>
#include "cxx.h"
#include "ffi.rs.h"

using namespace facebook;

namespace facebook {
namespace react {

template <typename T>
struct Bridging<rust::Vec<T>> {

  static rust::Vec<T> fromJs(jsi::Runtime& rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto arr = value.asObject(rt).asArray(rt);
    size_t len = arr.length(rt);
    rust::Vec<T> rsVec;
    rsVec.reserve(len);

    for (size_t i = 0; i < len; i++) {
      auto el = arr.getValueAtIndex(rt, i);
      rsVec.push_back(react::bridging::fromJs<T>(rt, el, callInvoker)));
    }

    return vec;
  }

  static jsi::Array toJs(jsi::Runtime& rt, const rust::Vec<T>& vec) {
    auto arr = jsi::Array(rt, vec.size());

    for (size_t i = 0; i < vec.size(); i++) {
      auto el = react::bridging::toJs(rt, vec[i]);
      arr.setValueAtIndex(rt, i, el);
    }

    return arr;
  }
};

template <>
struct Bridging<craby::crabytest::TestObject> {
  static craby::crabytest::TestObject fromJs(jsi::Runtime &rt, const jsi::Value &value, std::shared_ptr<CallInvoker> callInvoker) {
    auto obj = value.asObject(rt);
    auto obj$foo = obj.getProperty(rt, "foo");
    auto obj$bar = obj.getProperty(rt, "bar");
    auto obj$baz = obj.getProperty(rt, "baz");

    craby::crabytest::TestObject ret = {
      react::bridging::fromJs<std::string>(rt, obj$foo, callInvoker),
      react::bridging::fromJs<double>(rt, obj$bar, callInvoker),
      react::bridging::fromJs<bool>(rt, obj$baz, callInvoker)
    };

    return ret;
  }

  static jsi::Value toJs(jsi::Runtime &rt, craby::crabytest::TestObject value) {
    jsi::Object obj = jsi::Object(rt);
    obj.setProperty(rt, "foo", react::bridging::toJs(rt, std::string(value.foo)));
    obj.setProperty(rt, "bar", react::bridging::toJs(rt, value.bar));
    obj.setProperty(rt, "baz", react::bridging::toJs(rt, value.baz));
    return jsi::Value(rt, obj);
  }
};

template <>
struct Bridging<craby::crabytest::MyEnum> {
  static craby::crabytest::MyEnum fromJs(jsi::Runtime& rt, const jsi::Value& value, std::shared_ptr<CallInvoker> callInvoker) {
    auto raw = value.asString(rt).utf8(rt);
    if (raw == "FOO") {
      return craby::crabytest::MyEnum::FOO;
    } else if (raw == "BAR") {
      return craby::crabytest::MyEnum::BAR;
    } else if (raw == "BAZ") {
      return craby::crabytest::MyEnum::BAZ;
    } else {
      throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }

  static jsi::Value toJs(jsi::Runtime& rt, const craby::crabytest::MyEnum& value) {
    switch (value) {
      case craby::crabytest::MyEnum::FOO:
        return react::bridging::toJs(rt, std::string("FOO"));
      case craby::crabytest::MyEnum::BAR:
        return react::bridging::toJs(rt, std::string("BAR"));
      case craby::crabytest::MyEnum::BAZ:
        return react::bridging::toJs(rt, std::string("BAZ"));
      default:
        throw jsi::JSError(rt, "Invalid enum value (MyEnum)");
    }
  }
};

} // namespace react
} // namespace facebook
