// Auto generated by Craby. DO NOT EDIT.
#include "CxxCrabyTestModule.hpp"
#include "cxx.h"
#include "ffi.rs.h"

using namespace facebook;

namespace craby {
namespace crabytest {

CxxCrabyTestModule::CxxCrabyTestModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCrabyTestModule::kModuleName, jsInvoker) {
  callInvoker_ = std::move(jsInvoker);
  methodMap_["numericMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::numericMethod};
  methodMap_["booleanMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::booleanMethod};
  methodMap_["stringMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::stringMethod};
  methodMap_["objectMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::objectMethod};
  methodMap_["arrayMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::arrayMethod};
  methodMap_["enumMethod"] = MethodMetadata{1, &CxxCrabyTestModule::enumMethod};
  methodMap_["unionMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::unionMethod};
  methodMap_["promiseMethod"] =
      MethodMetadata{1, &CxxCrabyTestModule::promiseMethod};
}

jsi::Value CxxCrabyTestModule::numericMethod(jsi::Runtime &rt,
                                             react::TurboModule &turboModule,
                                             const jsi::Value args[],
                                             size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  if (1 == count && args[0].isNumber()) {
    auto arg0 = args[0].asNumber();
    auto ret = craby::ffi::numericMethod(arg0);
    return jsi::Value(ret);
  }

  throw jsi::JSError(rt, "Expected 1 argument (number)");
}

jsi::Value CxxCrabyTestModule::booleanMethod(jsi::Runtime &rt,
                                             react::TurboModule &turboModule,
                                             const jsi::Value args[],
                                             size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);

  if (1 == count && args[0].isBool()) {
    auto arg0 = react::bridging::fromJs<bool>(rt, args[0], thisModule.callInvoker_);
    auto ret = craby::ffi::booleanMethod(arg0);
    return react::bridging::toJs(rt, ret);
  }

  throw jsi::JSError(rt, "Expected 1 argument (boolean)");
}

jsi::Value CxxCrabyTestModule::stringMethod(jsi::Runtime &rt,
                                            react::TurboModule &turboModule,
                                            const jsi::Value args[],
                                            size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);

  if (1 == count && args[0].isString()) {
    auto arg0 = react::bridging::fromJs<std::string>(rt, args[0], thisModule.callInvoker_);
    auto ret = craby::ffi::stringMethod(arg0);
    return react::bridging::toJs(rt, std::string(ret));
  }

  throw jsi::JSError(rt, "Expected 1 argument (string)");
}

jsi::Value CxxCrabyTestModule::objectMethod(jsi::Runtime &rt,
                                            react::TurboModule &turboModule,
                                            const jsi::Value args[],
                                            size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  if (1 == count && args[0].isObject()) {
    auto testObject = react::bridging::fromJs<craby::ffi::TestObject>(rt, args[0], thisModule.callInvoker_);
    auto ret = craby::ffi::objectMethod(testObject);
    return react::bridging::toJs(rt, ret);
  }

  throw jsi::JSError(rt, "Expected 1 argument (string)");
}

jsi::Value CxxCrabyTestModule::arrayMethod(jsi::Runtime &rt,
                                           react::TurboModule &turboModule,
                                           const jsi::Value args[],
                                           size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  if (1 == count && args[0].isObject()) {
    auto arg0 = react::bridging::fromJs<rust::Vec<double>>(rt, args[0], thisModule.callInvoker_);
    auto ret = craby::ffi::arrayMethod(arg0);
    return react::bridging::toJs(rt, ret);
  }

  throw jsi::JSError(rt, "Expected 1 argument (array)");
}

jsi::Value CxxCrabyTestModule::enumMethod(jsi::Runtime &rt,
                                          react::TurboModule &turboModule,
                                          const jsi::Value args[],
                                          size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  if (1 == count && args[0].isString()) {
    auto arg0 = react::bridging::fromJs<craby::ffi::MyEnum>(rt, args[0], thisModule.callInvoker_);
    auto ret = craby::ffi::enumMethod(arg0);
    return react::bridging::toJs(rt, std::string(ret));
  }

  throw jsi::JSError(rt, "Expected 1 argument (string)");
}

jsi::Value CxxCrabyTestModule::unionMethod(jsi::Runtime &rt,
                                           react::TurboModule &turboModule,
                                           const jsi::Value args[],
                                           size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  if (1 == count && args[0].isString()) {
    auto arg0 = args[0].asString(rt).utf8(rt);

    if (!(arg0 == "up" || arg0 == "down" || arg0 == "left" ||
          arg0 == "right")) {
      throw jsi::JSError(rt, "Invalid union argument");
    }

    auto ret = jsi::String::createFromUtf8(
        rt, std::string(craby::ffi::unionMethod(arg0.c_str())));
    return jsi::Value(rt, ret);
  }

  throw jsi::JSError(rt, "Expected 1 argument (string)");
}

jsi::Value CxxCrabyTestModule::promiseMethod(jsi::Runtime &rt,
                                             react::TurboModule &turboModule,
                                             const jsi::Value args[],
                                             size_t count) {
  auto &thisModule = static_cast<CxxCrabyTestModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;

  auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);

  react::AsyncPromise<double> promise(rt, callInvoker);

  std::thread([&rt, arg0, promise]() mutable {
    try {
      auto ret = craby::ffi::promiseMethod(arg0);
      promise.resolve(ret);
    } catch (const std::exception &err) {
      const auto* rs_err = dynamic_cast<const rust::Error*>(&err);
      auto msg = std::string(rs_err ? rs_err->what() : err.what());
      promise.reject(msg);
    }
  }).detach();

  return react::bridging::toJs(rt, promise);
}

} // namespace crabytest
} // namespace craby
