// Auto generated by Craby. DO NOT EDIT.
#include "CxxCalculatorModule.hpp"

#include <thread>
#include <react/bridging/Bridging.h>

#include "cxx.h"
#include "ffi.rs.h"
#include "bridging-generated.hpp"
#include "utils.hpp"

#include <os/log.h>

using namespace facebook;

namespace craby {
namespace calculator {

CxxCalculatorModule::~CxxCalculatorModule() {
  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& registry = craby::eventemitter::EventEmitterRegistry::getInstance();
  registry.unregisterDelegate(id);
  os_log(OS_LOG_DEFAULT, "[C++] Unregisterd: %lu", id);
}

CxxCalculatorModule::CxxCalculatorModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCalculatorModule::kModuleName, jsInvoker) {
  callInvoker_ = std::move(jsInvoker);

  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& registry = craby::eventemitter::EventEmitterRegistry::getInstance();
  registry.registerDelegate(id,
                            [id](std::string name) {
                              os_log(OS_LOG_DEFAULT, "[C++] From Rust: %s (Module: %lu)", name.c_str(), id);
                            });
  os_log(OS_LOG_DEFAULT, "[C++] Registered: %lu", id);

  methodMap_["add"] = MethodMetadata{2, &CxxCalculatorModule::add};
  methodMap_["subtract"] = MethodMetadata{2, &CxxCalculatorModule::subtract};
  methodMap_["multiply"] = MethodMetadata{2, &CxxCalculatorModule::multiply};
  methodMap_["divide"] = MethodMetadata{2, &CxxCalculatorModule::divide};
}

jsi::Value CxxCalculatorModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::add(arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::subtract(arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::multiply(arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

jsi::Value CxxCalculatorModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCalculatorModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::bridging::divide(arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, errorMessage(err));
  }
}

} // namespace calculator
} // namespace craby
