// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <thread>
#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>
#include <jsi/jsi.h>

#include "bridging.hpp"

namespace craby {
namespace crabytest {

class JSI_EXPORT CxxCrabyTestModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "CrabyTest";

  CxxCrabyTestModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);

  static facebook::jsi::Value
  numericMethod(facebook::jsi::Runtime &rt,
                facebook::react::TurboModule &turboModule,
                const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  booleanMethod(facebook::jsi::Runtime &rt,
                facebook::react::TurboModule &turboModule,
                const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  stringMethod(facebook::jsi::Runtime &rt,
               facebook::react::TurboModule &turboModule,
               const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  objectMethod(facebook::jsi::Runtime &rt,
               facebook::react::TurboModule &turboModule,
               const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  arrayMethod(facebook::jsi::Runtime &rt,
              facebook::react::TurboModule &turboModule,
              const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  enumMethod(facebook::jsi::Runtime &rt,
             facebook::react::TurboModule &turboModule,
             const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  unionMethod(facebook::jsi::Runtime &rt,
              facebook::react::TurboModule &turboModule,
              const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  promiseMethod(facebook::jsi::Runtime &rt,
                facebook::react::TurboModule &turboModule,
                const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
};

} // namespace crabytest
} // namespace craby
