// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include <thread>
#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>
#include <jsi/jsi.h>

#include "cxx.h"
#include "ffi.rs.h"
#include "craby-bridging.hpp"

namespace craby {
namespace helpers {

inline std::string errorMessage(const std::exception &err) {
  const auto* rs_err = dynamic_cast<const rust::Error*>(&err);
  return std::string(rs_err ? rs_err->what() : err.what());
}

} // namespace helpers

namespace crabytest {

class JSI_EXPORT CxxCrabyTestModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "CrabyTest";

  CxxCrabyTestModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);

  static facebook::jsi::Value
  numericMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  booleanMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  stringMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  objectMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  arrayMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  enumMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  promiseMethod(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
};

} // namespace crabytest
} // namespace craby
