// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "ffi.rs.h"
#include "ThreadPool.hpp"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace calculator {

class JSI_EXPORT CxxCalculatorModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "Calculator";

  CxxCalculatorModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxCalculatorModule();

  void invalidate();
  static facebook::jsi::Value
  add(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  divide(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  multiply(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  subtract(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::bridging::Calculator> module_;
  std::shared_ptr<ThreadPool> threadPool_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
};

} // namespace calculator
} // namespace craby
