name: CI
env:
  DEBUG: napi:*
  APP_NAME: cli
  PACKAGE_NAME: '@craby/cli'
  PACKAGE_PATH: packages/cli
  MACOSX_DEPLOYMENT_TARGET: '10.13'

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              RUST_TARGET=x86_64-apple-darwin yarn workspace @craby/cli build

          - host: windows-latest
            build: |
              RUST_TARGET=x86_64-pc-windows-msvc yarn workspace @craby/cli build
            target: x86_64-pc-windows-msvc

          - host: windows-latest
            build: |
              RUST_TARGET=i686-pc-windows-msvc yarn workspace @craby/cli build
            target: i686-pc-windows-msvc

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |
              RUST_TARGET=x86_64-unknown-linux-gnu NAPI_FLAGS="--use-napi-cross" yarn workspace @craby/cli build

          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: RUST_TARGET=x86_64-unknown-linux-musl NAPI_FLAGS="--cross-compile" yarn workspace @craby/cli build

          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              RUST_TARGET=aarch64-apple-darwin yarn workspace @craby/cli build

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: |
              RUST_TARGET=aarch64-unknown-linux-gnu NAPI_FLAGS="--use-napi-cross" yarn workspace @craby/cli build

          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: |
              RUST_TARGET=armv7-unknown-linux-gnueabihf NAPI_FLAGS="--use-napi-cross" yarn workspace @craby/cli build

          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: |
              RUST_TARGET=aarch64-unknown-linux-musl NAPI_FLAGS="--cross-compile" yarn workspace @craby/cli build

          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: |
              RUST_TARGET=aarch64-pc-windows-msvc yarn workspace @craby/cli build

    name: stable - ${{ matrix.settings.target }} - node@22
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 22
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - uses: goto-bus-stop/setup-zig@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        with:
          version: 0.14.1
      - name: Install cargo-zigbuild
        uses: taiki-e/install-action@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Enable Corepack
        run: corepack enable
      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn workspaces focus ${{ env.PACKAGE_NAME }}
      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.PACKAGE_PATH }}/napi/${{ env.APP_NAME }}.*.node
          if-no-files-found: error

  build-freebsd:
    runs-on: ubuntu-latest
    name: Build FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        uses: cross-platform-actions/action@v0.29.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: '14.2'
          memory: 8G
          cpu_count: 3
          environment_variables: 'DEBUG RUSTUP_IO_THREADS'
          shell: bash
          run: |
            sudo pkg install -y -f curl node libnghttp2 npm cmake
            sudo corepack enable
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            source "$HOME/.cargo/env"
            echo "~~~~ rustc --version ~~~~"
            rustc --version
            echo "~~~~ node -v ~~~~"
            node -v
            echo "~~~~ yarn --version ~~~~"
            yarn --version
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            yarn workspaces focus ${{ env.PACKAGE_NAME }}
            yarn workspace ${{ env.PACKAGE_NAME }} build
            rm -rf node_modules
            rm -rf target
            rm -rf .yarn/cache
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-freebsd
          path: ${{ env.PACKAGE_PATH }}/napi/${{ env.APP_NAME }}.*.node
          if-no-files-found: error

  test-macOS-windows-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
        node:
          - '22'
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: x64
      - name: Enable Corepack
        run: corepack enable
      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn workspaces focus ${{ env.PACKAGE_NAME }}
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.PACKAGE_PATH }}/napi
      - name: List packages
        run: ls -R ${{ env.PACKAGE_PATH }}
        shell: bash
      - name: Test bindings
        run: yarn workspace @craby/cli test

  test-linux-binding:
    name: Test ${{ matrix.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
        node:
          - '22'
    runs-on: ${{ contains(matrix.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Enable Corepack
        run: corepack enable
      - name: Output docker params
        id: docker
        run: |
          node -e "
            if ('${{ matrix.target }}'.startsWith('aarch64')) {
              console.log('PLATFORM=linux/arm64')
            } else if ('${{ matrix.target }}'.startsWith('armv7')) {
              console.log('PLATFORM=linux/arm/v7')
            } else {
              console.log('PLATFORM=linux/amd64')
            }
          " >> $GITHUB_OUTPUT
          node -e "
            if ('${{ matrix.target }}'.endsWith('-musl')) {
              console.log('IMAGE=node:${{ matrix.node }}-alpine')
            } else {
              console.log('IMAGE=node:${{ matrix.node }}-slim')
            }
          " >> $GITHUB_OUTPUT
      - name: Restore Yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn workspaces focus ${{ env.PACKAGE_NAME }}
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: ${{ env.PACKAGE_PATH }}/napi
      - name: List packages
        run: ls -R ${{ env.PACKAGE_PATH }}
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ contains(matrix.target, 'armv7') }}
        with:
          platforms: all
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: ${{ contains(matrix.target, 'armv7') }}
      - name: Test bindings
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ steps.docker.outputs.IMAGE }}
          options: -v $(pwd):/build -w /build --platform ${{ steps.docker.outputs.PLATFORM }}
          run: sh -c "corepack enable && yarn workspace @craby/cli test"


  publish-bindings:
    name: Publish bindings
    runs-on: ubuntu-latest
    needs:
      - build-freebsd
      - test-macOS-windows-binding
      - test-linux-binding
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn workspaces focus ${{ env.PACKAGE_NAME }}
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.PACKAGE_PATH }}/artifacts
      - name: Move artifacts
        run: yarn workspace @craby/cli artifacts
      - name: List packages
        run: ls -R ${{ env.PACKAGE_PATH }}/npm
        shell: bash
      - name: Publish
        run: |
          cd ${{ env.PACKAGE_PATH }}
          yarn config set npmPublishRegistry "https://registry.npmjs.org/"
          yarn config set npmAuthToken "$NPM_TOKEN"
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn napi prepublish -t npm --skip-gh-release
            yarn npm publish --access public
          elif git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn napi prepublish -t npm --skip-gh-release
            yarn npm publish --tag next --access public
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
